[package]
name = "sum_error"
version = "0.1.0"
authors = ["bzik <alexander.bzikadze@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.7"
quote = "1.0.2"
proc-macro2 = "1.0.6"

[[bin]]
name = "test"
path = "src/test/lib.rs"
test = false
doc = false
